### ISSUE TITLE
Current Date

### ISSUE THREAD

**Issue by Serendipbrity** [Serendipbrity/Gators-Newsletter#1]
Add the current date to auto update at the top of the screen

**Comment by rvacovsky** [comment]
You mentioned we could use same logic from work day scheduler project (moment.js). For example:

<p id="currentDay"></p>


var currentDate = moment().format("dddd, MMMM Do");
$("#currentDay").text(currentDate);

**Comment by rvacovsky** [comment]
Date is set but would like to modify string that shows in HTML.

**Comment by rvacovsky** [comment]
Fixed the date by adding in code mentioned above AND switching the order of the sources in HTML. Also added Year (YYYY)
