### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Serendipbrity** [Serendipbrity/Gators-Newsletter#3]
Design layout/color scheme

**Comment by rvacovsky** [comment]
Majority of layout and styling is set. Will enhance look of content boxes by using accordion component. Add any lists, line breaks, new paragraphs, images where relevant. Any email address should be a clickable link.

**Comment by rvacovsky** [comment]
Added accordion to my feature branch. Also included pictures and changed the font color of a lot of the text to green. Started to work on potential current temperature API solution; placeholder is there now.
